name: Docker Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                platform: [
                    "linux/amd64",
                    "linux/arm64"
                ]
                tag: [
                    7,
                    7.2-fpm,
                    7.3-fpm-v1,
#                    7.3.6-fpm-v1,
#                    7.3.6-fpm-v2,
#                    7.3.6-fpm-v3,
                    7.3.7-fpm-v1,
                    7.3.7-fpm-v1,
                    7.4-fpm-v1,
                    7.4-fpm-v2,
                    7.4-fpm-v3,
                    7.4-fpm-v3.1,
                    7.4-fpm-composer-v1,
                    7.4-fpm-composer-v2,
                    8.0-fpm-base,
                    8.0-fpm-exif,
                    8.0-fpm-medialibrary,
                    8.1-fpm-base,
                    8.1-fpm-exif,
                    8.1-fpm-medialibrary,
                    8.2-fpm-base,
                    8.2-fpm-exif,
                    8.2-fpm-medialibrary,
                    8.3-fpm-base,
                    8.3-fpm-exif,
                    8.3-fpm-medialibrary,
                    8.4-fpm-base,
                    8.4-fpm-exif,
                    8.4-fpm-medialibrary,
                ]

        name: ${{ matrix.tag }} | ${{ matrix.platform }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install Docker buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    version: latest

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: sh build.sh ${{ matrix.tag }} ${{ matrix.platform }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'
