name: Docker Push

on:
  schedule:
    - cron: '5 3 2 * *'
  release:
    types: [published]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                tag: [
                    7,
                    7.2-fpm,
                    7.3-fpm-v1,
                    7.3.6-fpm-v1,
                    7.3.6-fpm-v2,
                    7.3.6-fpm-v3,
                    7.3.7-fpm-v1,
                    7.3.7-fpm-v1,
                    7.4-fpm-v1,
                    7.4-fpm-v2,
                    7.4-fpm-v3,
                    7.4-fpm-v3.1,
                    7.4-fpm-composer-v1,
                    7.4-fpm-composer-v2,
                    7.4-rc-fpm-v1,
                    8.0-fpm-v1,
                    8.0-fpm-v2,
                    8.0-fpm-v3,
                    8.1-fpm-v1,
                    8.1-fpm-v2,
                    8.1-fpm-v3,
                    8.1-rc-fpm-v1,
                    8.1-rc-fpm-v1.1,
                    8.1-rc-fpm-v2,
                ]

        name: TAG-${{ matrix.tag }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: bash build.sh ${{ matrix.tag }}

            -   name: Push Docker Image
                run: bash push.sh ${{ matrix.tag }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'